name: Check for Flyway Project

on:
  pull_request:
    types: [opened, edited]

jobs:
  call-flyway-project-workflow:
    uses: xcorp-devex/common/.github/workflows/check-for-flyway-project.yaml@28dd782e527159530046a013a1b128efe65f111e # main
    with:
      pr-number: ${{ github.event.pull_request.number }}
      repo-name: ${{ github.event.repository.name }}
      org-name: ${{ github.event.repository.owner.login }}
      runner-spec: '{"group": "devxm-x64-xsmall"}'
    secrets: inherit